version: '3'

services:
  moodmark:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://prisma:prisma@db:5432/moodmark
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=moodmark
